apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-charityyeti-proxy
spec:
  tls:
  - hosts:
      - https-charityyeti.casadecook.com
    secretName: charityyeti.casadecook.com
  rules:
  - host: charityyeti.casadecook.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: charityyeti-proxy
            port:
              number: 443
  ingressClassName: nginx
  