version: '3'
services:
    charityyeti:
        build:
            context: .
            dockerfile: Dockerfile
        image: williamcook/charityyeti
        env_file: .env
        ports:
            - "8080:8080"