version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: williamcook/charityyeti-backend:${TAG_VERSION}
        env_file: 
            - .env
        environment:
            - CONSUMER_KEY=${CONSUMER_KEY}
            - CONSUMER_SECRET=${CONSUMER_SECRET}
            - ACCESS_TOKEN=${ACCESS_TOKEN}
            - ACCESS_SECRET=${ACCESS_SECRET}
            - MONGO_URI=${MONGO_URI}
            - DATABASE=${DATABASE}
            - COLLECTION=${COLLECTION}
            - PORT=${PORT}
        ports:
            - "8080:8080"
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        image: williamcook/charityyeti-frontend:${TAG_VERSION}
        ports: 
            - "80:80"
    middleware:
        build:
            context: ./middleware
            dockerfile: ./CharityYetiServices/Dockerfile
        image: williamcook/charityyeti-middleware:${TAG_VERSION}
        env_file: 
            - .env
