version: '3'
services:
    charityyeti-backend:
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        # image: ${DOCKER_REGISTRY}/charity-yeti-test-backend:${TAG_VERSION}
        image: williamcook/charityyeti-backend:${TAG_VERSION}
        env_file: 
            - .env
        environment:
            - CONSUMER_KEY=${CONSUMER_KEY}
            - CONSUMER_SECRET=${CONSUMER_SECRET}
            - ACCESS_TOKEN=${ACCESS_TOKEN}
            - ACCESS_SECRET=${ACCESS_SECRET}
            - MONGO_URI=${MONGO_URI}
            - DATABASE=${DATABASE}
            - COLLECTION=${COLLECTION}
            - PORT=${PORT}
            - SEND_TWEETS=${SEND_TWEETS}
            - BLOCK_LIST=${BLOCK_LIST}
            - BEARER_TOKEN=${BEARER_TOKEN}
            - WEBHOOK_CALLBACK_URL=${WEBHOOK_CALLBACK_URL}
            - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
            - CHARITY_YETI_ID=${CHARITY_YETI_ID}
        # ports:
        #     - "8080:8080"
    charityyeti-frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        # image: ${DOCKER_REGISTRY}/charity-yeti-test-frontend:${TAG_VERSION}
        image: williamcook/charityyeti-frontend:${TAG_VERSION}
        # ports: 
        #     - "8082:80"
    charityyeti-proxy:
        build:
            context: .
            dockerfile: docker/Dockerfile.proxy
        image: williamcook/charityyeti-proxy:${TAG_VERSION}
        ports:
            - "80:80"
            - "443:443"
