apiVersion: apps/v1
kind: Deployment
metadata:
  name: charityyeti-frontend
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: charityyeti-frontend
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: charityyeti-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: charityyeti-frontend
        image: docker.io/williamcook/charityyeti-frontend:kates
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: charityyeti-frontend
  labels:
    app.kubernetes.io/name: charityyeti-frontend
    app.kubernetes.io/component: frontend
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 80
  selector:
    app.kubernetes.io/name: charityyeti-frontend
    app.kubernetes.io/component: frontend
  type: ClusterIP