apiVersion: apps/v1
kind: Deployment
metadata:
  name: charityyeti-proxy
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: charityyeti-proxy
      app.kubernetes.io/component: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: charityyeti-proxy
        app.kubernetes.io/component: proxy
    spec:
      containers:
      - name: charityyeti-proxy
        image: williamcook/charityyeti-proxy:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: charityyeti-proxy
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy