apiVersion: v1
kind: Service
metadata:
  name: charityyeti-proxy
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  selector:
    app.kubernetes.io/name: charityyeti
  type: ClusterIP