apiVersion: apps/v1
kind: Deployment
metadata:
  name: charityyeti-frontend
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: charityyeti-frontend
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: charityyeti-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: charityyeti-frontend
        image: williamcook/charityyeti-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8082
    imagePullSecrets:
    - name: regcred
