apiVersion: v1
kind: Service
metadata:
  name: charityyeti-frontend
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: frontend