apiVersion: v1
kind: Service
metadata:
  name: charityyeti-proxy
  labels:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: charityyeti
    app.kubernetes.io/component: proxy